name: Generate Datas

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Geração da animação com permissão explícita de leitura do perfil
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: WendersonPereiraLopes
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy dos arquivos para a branch 'output'
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
